/**
 * This example is a part of coursework and carries educational purposes, generated by OpenAI's ChatGPT.
 *
 * The support services are linked in a chain (Technical -> Billing -> Managerial)
 * and the sender sends a Managerial support request. This request is passed through the chain
 * until it reaches a handler capable of processing it (the ManagerialSupport handler).
 *
 * SupportService defines a default behavior for handling requests.
 * Each support level (TechnicalSupport, BillingSupport, ManagerialSupport)
 * represents a concrete handler in the chain.
 */
public class Main {
    public static void main(String[] args) {
        SupportService techSupport = new TechnicalSupport();
        SupportService billingSupport = new BillingSupport();
        SupportService managerialSupport = new ManagerialSupport();

        techSupport.setNext(billingSupport);
        billingSupport.setNext(managerialSupport);

        // Request
        techSupport.handleRequest(new SupportRequest(SupportRequestType.MANAGERIAL));
    }
}