/**
 * This is an example for use of the Mediator Pattern generated by ChatGPT.
 * Objects communicate through a mediator, so less dependency between.
 * The communication between Aircraft (colleague) is managed centrally with the ControlTower (mediator).
 *
 * It is not implementing any system that deals with safety-critical tasks.
*/
public class Main {
    public static void main(String[] args) {
        ControlTower controlTower = new AirTrafficControlTower();

        Plane plane1 = new Plane(controlTower, "Flight 101");
        Plane plane2 = new Plane(controlTower, "Flight 202");
        Plane plane3 = new Plane(controlTower, "Flight 303");

        plane1.send("This is from flight 101");
        plane2.send("This is from flight 202");
        plane3.send("Flight 303 at holding point A1, ready for takeoff.");
    }
}
